# DO NOT EDIT THIS FILE!
#
# Python module NetOpp__POA generated by omniidl

import omniORB
omniORB.updateModule("NetOpp__POA")

# ** 1. Stub files contributing to this module
import netopp_idl

# ** 2. Sub-modules

# ** 3. End
