# DO NOT EDIT THIS FILE!
#
# Python module NetOpp generated by omniidl

import omniORB
omniORB.updateModule("NetOpp")

# ** 1. Stub files contributing to this module
import netopp_idl

# ** 2. Sub-modules

# ** 3. End
