#!/bin/bash

rm -rf /usr/share/dbus-1/system-services/fi.w1.wpa_supplicant1.service
rm -rf /etc/blackbox

mkdir -p /etc/blackbox/carro/videos/
mkdir -p /etc/blackbox/carro/wpa/
mkdir -p /etc/blackbox/carro/log/

chmod 777 /etc/blackbox
chmod 777 /etc/blackbox/carro
chmod 777 /etc/blackbox/carro/videos
chmod 777 /etc/blackbox/carro/wpa
chmod 777 /etc/blackbox/carro/log

cp ./carro-client.jar /etc/blackbox/carro/
cp ./carro-init /etc/init.d/
cp ./carro-gravacao.sh /etc/blackbox/carro/
cp ./carro-init /etc/blackbox/carro/
cp ./carro-wpa /etc/blackbox/carro/wpa/
cp ./carro-wpa.conf /etc/blackbox/carro/wpa/
cp ./carro-dhcp /etc/blackbox/carro/wpa/
cp ./config.properties /etc/blackbox/carro/
cp ./videos.txt /etc/blackbox/carro/log/
cp ./gravacao.py /etc/blackbox/carro/
cp ./verifica-espaco.py /etc/blackbox/carro/
cp ./carro-verifica-espaco.sh /etc/blackbox/carro/

chmod 777 /etc/blackbox/carro/carro-client.jar
chmod 777 /etc/init.d/carro-init
chmod 777 /etc/blackbox/carro/carro-gravacao.sh
chmod 777 /etc/blackbox/carro/carro-verifica-espaco.sh
chmod 777 /etc/blackbox/carro/carro-init
chmod 777 /etc/blackbox/carro/wpa/carro-wpa
chmod 777 /etc/blackbox/carro/wpa/carro-wpa.conf
chmod 777 /etc/blackbox/carro/wpa/carro-dhcp
chmod 777 /etc/blackbox/carro/config.properties
chmod 777 /etc/blackbox/carro/gravacao.py
chmod 777 /etc/blackbox/carro/verifica-espaco.py
chmod 777 /etc/blackbox/carro/log/videos.txt

update-rc.d -f carro-init remove
update-rc.d carro-init defaults
